### ISSUE TITLE
Trig seasonality assumes only one seasonal component.

### ISSUE THREAD

**Issue by steve-the-bayesian** [steve-the-bayesian/BOOM#40]
Adding multiple cycles (via addTrig), but output only returns sd of one.

Reproducible (and artificial example):
library(bsts)
data(AirPassengers)
y <- log(AirPassengers)
ss <- AddLocalLinearTrend(list(), y)
ss <- AddTrig(ss, y, period = 20, frequencies = 1)
ss <- AddTrig(ss, y, period = 41, frequencies = 1)

model <- bsts(y, state.specification = ss, niter = 500)

only one available:
model$trig.coefficient.sd

Thanks,
Alexios

**Comment by alexiosg** [comment]
I checked the and it does return the correct number of number of trig.coefficient.sd, but because they have the same name (unlike the seasonal component which is appended with its period e.g. sigma.seasonal.12) and so is not immediately seen if trying to access it via a name, but can be access by its slot number. Suggestion, rename the trig.coefficient.sd to include some identifying information e.g. trig20.coefficient.sd.

**Comment by steve-the-bayesian** [comment]
Makes sense, and that works like the time domain seasonal models.

**Comment by steve-the-bayesian** [comment]
Trig components now indexed by period.
