### ISSUE TITLE
Running bsts with SharedLocalLevel model gives error with respect to class

### ISSUE THREAD

**Issue by wpverbeek** [steve-the-bayesian/BOOM#60]
When using the AddSharedLocalLevel state component, the BSTS function gives an error with respect to the class off the SS object:
Code:
```
ss2 <- AddSharedLocalLevel(list(), y_train,nfactors=1, timestamps=timestamps_train,series.id=series_train)
model2 <- bsts(y_train ~ predictor_train, ss2, niter = 250, timestamps = timestamps_train,
              seed = 8675309)
```
Error:
```
Error in bsts(y_train ~ predictor_train, ss2, niter = 250, timestamps = timestamps_train,  : 
  Caught exception with the following error message: 
Unknown object passed where state model expected.
Object has class:
     SharedLocalLevel
     SharedStateModel
```
The object is constructed as follows:
![image](https://user-images.githubusercontent.com/9164013/148092662-1f17d92d-b342-4376-adc3-5c93c2378b92.png)
which seems fine.....

This happens only with a SharedLocalLevel. Assuming one Local level, using the following code, gives no problems and runs fine:
```
ss1 <- AddLocalLevel(list(), y_train)
model1 <- bsts(y_train ~ predictor_train, ss1, niter = 250, timestamps = timestamps_train,
seed = 8675309)
```

This seems to be a bug, or did I made mistakes with calling these functions?

**Comment by steve-the-bayesian** [comment]
You should not be able to run bsts with SharedLocalLevel.  SharedLocalLevel is a state model intended for use with multivariate outcomes, which the bsts function does not support.  There is an unpublished 'mbsts' function that I had to rip out because it was failing some unit tests on CRAN.  I have recently updated mbsts in the repo, but not pushed those changes to CRAN.

To install from the repo, pull the latest `dev` branch, navigate to the project root, and run the following scripts:
```
./install/create_boom_rpackage -i
./install/boom_spike_slab -i
./install/bsts -i
```

**Comment by steve-the-bayesian** [comment]
commit 4fa64964e5c638d558c6183e2b60b9adeb835e47 adds a check that all state.specification elements are StateModel objects.
